/* Auto-generated by convert_font.py on 2025-12-26T07:37:07.069265Z */
#include "fonts.h"
#include <stddef.h>

static const FontDescriptor fonts[] = {
#ifdef SSD1306_INCLUDE_FONT_6x8
    { "Font_6x8", &Font_6x8, 6, 8 },
#endif
#ifdef SSD1306_INCLUDE_FONT_7x10
    { "Font_7x10", &Font_7x10, 7, 10 },
#endif
#ifdef SSD1306_INCLUDE_FONT_11x18
    { "Font_11x18", &Font_11x18, 11, 18 },
#endif
#ifdef SSD1306_INCLUDE_FONT_16x26
    { "Font_16x26", &Font_16x26, 16, 26 },
#endif
#ifdef SSD1306_INCLUDE_FONT_16x24
    { "Font_16x24", &Font_16x24, 16, 24 },
#endif
#ifdef SSD1306_INCLUDE_FONT_16x15
    { "Font_16x15", &Font_16x15, 16, 15 },
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_12x15
    { "fontBlenderProBold14pt12x15", &fontBlenderProBold14pt12x15, 12, 15 },
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_11x15
    { "fontBlenderProBold15pt11x15", &fontBlenderProBold15pt11x15, 11, 15 },
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_12x17
    { "fontBlenderProBold16pt12x17", &fontBlenderProBold16pt12x17, 12, 17 },
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_12x18
    { "fontBlenderProBold17pt12x18", &fontBlenderProBold17pt12x18, 12, 18 },
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_13x19
    { "fontBlenderProBold18pt13x19", &fontBlenderProBold18pt13x19, 13, 19 },
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_14x20
    { "fontBlenderProBold19pt14x20", &fontBlenderProBold19pt14x20, 14, 20 },
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x24
    { "fontEthnocentric25pt32x24", &fontEthnocentric25pt32x24, 32, 24 },
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x25
    { "fontEthnocentric26pt32x25", &fontEthnocentric26pt32x25, 32, 25 },
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x26
    { "fontEthnocentric27pt32x26", &fontEthnocentric27pt32x26, 32, 26 },
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x27
    { "fontEthnocentric28pt32x27", &fontEthnocentric28pt32x27, 32, 27 },
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x28
    { "fontEthnocentric29pt32x28", &fontEthnocentric29pt32x28, 32, 28 },
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x29
    { "fontEthnocentric30pt32x29", &fontEthnocentric30pt32x29, 32, 29 },
#endif
#ifdef SSD1306_MINECRAFT_FONT_10x12
    { "fontMinecraft11pt10x12", &fontMinecraft11pt10x12, 10, 12 },
#endif
#ifdef SSD1306_MINECRAFT_FONT_11x12
    { "fontMinecraft12pt11x12", &fontMinecraft12pt11x12, 11, 12 },
#endif
#ifdef SSD1306_MINECRAFT_FONT_12x14
    { "fontMinecraft13pt12x14", &fontMinecraft13pt12x14, 12, 14 },
#endif
#ifdef SSD1306_MINECRAFT_FONT_13x15
    { "fontMinecraft14pt13x15", &fontMinecraft14pt13x15, 13, 15 },
#endif
#ifdef SSD1306_MINECRAFT_FONT_14x16
    { "fontMinecraft15pt14x16", &fontMinecraft15pt14x16, 14, 16 },
#endif
#ifdef SSD1306_MINECRAFT_FONT_14x16
    { "fontMinecraft16pt14x16", &fontMinecraft16pt14x16, 14, 16 },
#endif
};

const FontDescriptor *fonts_get_all(size_t *out_count)
{
    if (out_count) *out_count = sizeof(fonts)/sizeof(fonts[0]);
    return fonts;
}

const SSD1306_Font_t *fonts_find_by_size(uint8_t width, uint8_t height)
{
    size_t n = sizeof(fonts)/sizeof(fonts[0]);
    for (size_t i = 0; i < n; ++i) {
        if (fonts[i].width == width && fonts[i].height == height)
            return fonts[i].font;
    }
    return NULL;
}

const SSD1306_Font_t *fonts_get_default(void)
{
#ifdef SSD1306_INCLUDE_FONT_9x12
    return &fontBlenderProBold11pt9x12;
#endif
#ifdef SSD1306_INCLUDE_FONT_11x18
    return &Font_11x18;
#endif
    size_t n = sizeof(fonts)/sizeof(fonts[0]);
    if (n > 0) return fonts[0].font;
    return NULL;
}
