/**
 ******************************************************************************
 * @file    config.h
 * @brief   Centralized configuration for Ember hotplate
 * @date    December 16, 2025
 ******************************************************************************
 */

#ifndef CONFIG_H
#define CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * System Configuration
 * ============================================================================ */
#define SYSTEM_CLOCK_HZ         64000000    // 64 MHz system clock

/* ============================================================================
 * Heater PWM Configuration (TIM2 CH1)
 * ============================================================================ */
#define HEATER_TIM_CLOCK_HZ     64000000    // Timer clock frequency
#define HEATER_PWM_FREQ_HZ      10          // PWM frequency (10 Hz for SSR/MOSFET)
#define HEATER_PWM_RESOLUTION   1000        // 0-1000 = 0.0% to 100.0% duty cycle

// Calculated timer values (do not modify)
#define HEATER_TIM_PRESCALER    ((HEATER_TIM_CLOCK_HZ / (HEATER_PWM_FREQ_HZ * HEATER_PWM_RESOLUTION)) - 1)
#define HEATER_TIM_PERIOD       (HEATER_PWM_RESOLUTION - 1)

/* ============================================================================
 * Speaker PWM Configuration (TIM1 CH1)
 * ============================================================================ */
#define SPEAKER_TIM_CLOCK_HZ    64000000    // Timer clock frequency

/* ============================================================================
 * Encoder Configuration (LPTIM1)
 * ============================================================================ */
#define ENCODER_COUNTS_PER_DETENT   2       // Encoder counts per click/detent

/* ============================================================================
 * Button Configuration
 * ============================================================================ */
#define BUTTON_DEBOUNCE_MS      30          // Button debounce time (ms)
#define BUTTON_LONG_PRESS_MS    500         // Long press threshold (ms)

/* ============================================================================
 * I2C Device Addresses
 * ============================================================================ */
#define TPS25730_I2C_ADDRESS    0x20        // USB-PD controller
#define TMP116_I2C_ADDR         0x48        // Temperature sensor (ADD0 = GND)
#define NFC_I2C_ADDRESS         0x55        // NT3H2111 NFC tag (7-bit address, byte=0x08)
#define OLED_I2C_ADDRESS        0xC3        // OLED display (7-bit address, byte=0xC3)

/* ============================================================================
 * NFC Configuration
 * ============================================================================ */
#define NFC_I2C_TIMEOUT_MS      100         // I2C timeout for NFC operations
#define NFC_POLL_INTERVAL_MS    100         // NFC polling interval (ms)

/* ============================================================================
 * Temperature Limits
 * ============================================================================ */
#define TEMP_MAX_CELSIUS        300.0f      // Maximum allowed temperature
#define TEMP_MIN_CELSIUS        0.0f        // Minimum operating temperature
#define TEMP_READ_INTERVAL_MS   500         // Temperature polling interval (ms)

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T06:44:46.102303Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:20:40.840710Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:20:44.743765Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:21:07.425289Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:21:52.484942Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:32:00.635073Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:35:39.336429Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */

/* ---------------------------------------------------------------------------
 * SSD1306 Font selection (auto-generated) - edit inside USER CODE block
 * Generated by Scripts/convert_font.py on 2025-12-26T07:37:07.085500Z
 * To enable a font, remove the "// " prefix from the corresponding line below
 */
/* USER CODE BEGIN SSD1306_FONTS */

/* Built-in fonts */
#define SSD1306_INCLUDE_FONT_6x8
#define SSD1306_INCLUDE_FONT_7x10
#define SSD1306_INCLUDE_FONT_11x18
#define SSD1306_INCLUDE_FONT_16x15
#define SSD1306_INCLUDE_FONT_16x24
#define SSD1306_INCLUDE_FONT_16x26

/* 3rd-party / family fonts */
// #define SSD1306_MINECRAFT_FONT_10x12
// #define SSD1306_MINECRAFT_FONT_11x12
#define SSD1306_BLENDER_PRO_BOLD_FONT_11x15
// #define SSD1306_MINECRAFT_FONT_12x14
#define SSD1306_BLENDER_PRO_BOLD_FONT_12x15
#define SSD1306_BLENDER_PRO_BOLD_FONT_12x17
#define SSD1306_BLENDER_PRO_BOLD_FONT_12x18
// #define SSD1306_MINECRAFT_FONT_13x15
#define SSD1306_BLENDER_PRO_BOLD_FONT_13x19
// #define SSD1306_MINECRAFT_FONT_14x16
#define SSD1306_BLENDER_PRO_BOLD_FONT_14x20
#define SSD1306_ETHNOCENTRIC_FONT_32x24
#define SSD1306_ETHNOCENTRIC_FONT_32x25
#define SSD1306_ETHNOCENTRIC_FONT_32x26
#define SSD1306_ETHNOCENTRIC_FONT_32x27
#define SSD1306_ETHNOCENTRIC_FONT_32x28
#define SSD1306_ETHNOCENTRIC_FONT_32x29

/* USER CODE END SSD1306_FONTS */

#ifdef __cplusplus
}
#endif


// --- Auto-generated font options (convert_font.py) ---
// Uncomment to enable fonts (uncomment only the fonts you need to save flash)
// --- End auto-generated font options ---










#endif /* CONFIG_H */
