/* Auto-generated by convert_font.py on 2025-12-26T07:37:07.069265Z */
#ifndef __FONTS_H__
#define __FONTS_H__

#include "ssd1306_fonts.h"
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *name;
    const SSD1306_Font_t *font;
    uint8_t width;
    uint8_t height;
} FontDescriptor;

const FontDescriptor *fonts_get_all(size_t *out_count);
const SSD1306_Font_t *fonts_find_by_size(uint8_t width, uint8_t height);
const SSD1306_Font_t *fonts_get_default(void);

#ifdef __cplusplus
}
#endif

#endif /* __FONTS_H__ */
