/* Generated by convert_font.py from BlenderPro-Bold.ttf on 2025-12-26T05:59:09.361925Z */
#ifndef BLENDERPROBOLD_H
#define BLENDERPROBOLD_H

#include "ssd1306_fonts.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_12x15
extern const SSD1306_Font_t fontBlenderProBold14pt12x15;
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_11x15
extern const SSD1306_Font_t fontBlenderProBold15pt11x15;
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_12x17
extern const SSD1306_Font_t fontBlenderProBold16pt12x17;
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_12x18
extern const SSD1306_Font_t fontBlenderProBold17pt12x18;
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_13x19
extern const SSD1306_Font_t fontBlenderProBold18pt13x19;
#endif
#ifdef SSD1306_BLENDER_PRO_BOLD_FONT_14x20
extern const SSD1306_Font_t fontBlenderProBold19pt14x20;
#endif

#ifdef __cplusplus
}
#endif

#endif /* BLENDERPROBOLD_H */
