/* Generated by convert_font.py from Ethnocentric.otf on 2025-12-26T07:21:52.458039Z */
#ifndef ETHNOCENTRIC_H
#define ETHNOCENTRIC_H

#include "ssd1306_fonts.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SSD1306_ETHNOCENTRIC_FONT_16x13
extern const SSD1306_Font_t fontEthnocentric13pt16x13;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_16x14
extern const SSD1306_Font_t fontEthnocentric14pt16x14;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_16x15
extern const SSD1306_Font_t fontEthnocentric15pt16x15;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_16x16
extern const SSD1306_Font_t fontEthnocentric16pt16x16;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_16x17
extern const SSD1306_Font_t fontEthnocentric17pt16x17;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_16x18
extern const SSD1306_Font_t fontEthnocentric18pt16x18;
#endif

#ifdef __cplusplus
}
#endif

#endif /* ETHNOCENTRIC_H */
