/* Generated by convert_font.py from Ethnocentric.otf on 2025-12-26T07:32:00.613485Z */
#ifndef ETHNOCENTRIC_H
#define ETHNOCENTRIC_H

#include "ssd1306_fonts.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SSD1306_ETHNOCENTRIC_FONT_32x24
extern const SSD1306_Font_t fontEthnocentric25pt32x24;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x25
extern const SSD1306_Font_t fontEthnocentric26pt32x25;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x26
extern const SSD1306_Font_t fontEthnocentric27pt32x26;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x27
extern const SSD1306_Font_t fontEthnocentric28pt32x27;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x28
extern const SSD1306_Font_t fontEthnocentric29pt32x28;
#endif
#ifdef SSD1306_ETHNOCENTRIC_FONT_32x29
extern const SSD1306_Font_t fontEthnocentric30pt32x29;
#endif

#ifdef __cplusplus
}
#endif

#endif /* ETHNOCENTRIC_H */
