/* Generated by convert_font.py from Minecraft.ttf on 2025-12-26T05:37:08.455885Z */
#ifndef MINECRAFT_H
#define MINECRAFT_H

#include "ssd1306_fonts.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SSD1306_MINECRAFT_FONT_10x12
extern const SSD1306_Font_t fontMinecraft11pt10x12;
#endif
#ifdef SSD1306_MINECRAFT_FONT_11x12
extern const SSD1306_Font_t fontMinecraft12pt11x12;
#endif
#ifdef SSD1306_MINECRAFT_FONT_12x14
extern const SSD1306_Font_t fontMinecraft13pt12x14;
#endif
#ifdef SSD1306_MINECRAFT_FONT_13x15
extern const SSD1306_Font_t fontMinecraft14pt13x15;
#endif
#ifdef SSD1306_MINECRAFT_FONT_14x16
extern const SSD1306_Font_t fontMinecraft15pt14x16;
#endif
#ifdef SSD1306_MINECRAFT_FONT_14x16
extern const SSD1306_Font_t fontMinecraft16pt14x16;
#endif

#ifdef __cplusplus
}
#endif

#endif /* MINECRAFT_H */
