name= Oled UI Components
version=1.0.1
author=BG Okcu
maintainer=bgo <bugraokcu@gmail.com>
sentence=SSD1306 oled UI components for building UI.
paragraph=SSD1306 oled UI components for building UI with a component-based architecture. Depends on Adafruit_SSD1306.
category=Display
url=https://github.com/bgo/oled-ui-lib
architectures=*
depends=Adafruit SSD1306