/* Generated by convert_font.py from BlenderPro-Bold.ttf on 2025-12-26T04:22:07.631759Z */
#ifndef BLENDERPROBOLD_H
#define BLENDERPROBOLD_H

#include "ssd1306_fonts.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SSD1306_INCLUDE_FONT_9x12
extern const SSD1306_Font_t fontBlenderProBold11pt9x12;
#endif
#ifdef SSD1306_INCLUDE_FONT_9x13
extern const SSD1306_Font_t fontBlenderProBold12pt9x13;
#endif
#ifdef SSD1306_INCLUDE_FONT_11x14
extern const SSD1306_Font_t fontBlenderProBold13pt11x14;
#endif
#ifdef SSD1306_INCLUDE_FONT_12x15
extern const SSD1306_Font_t fontBlenderProBold14pt12x15;
#endif
#ifdef SSD1306_INCLUDE_FONT_11x15
extern const SSD1306_Font_t fontBlenderProBold15pt11x15;
#endif
#ifdef SSD1306_INCLUDE_FONT_12x17
extern const SSD1306_Font_t fontBlenderProBold16pt12x17;
#endif

#ifdef __cplusplus
}
#endif

#endif /* BLENDERPROBOLD_H */
