// Generated by musicxml_to_speaker_notes.py
// From ./swallow.musicxml, tempo=154.0
#ifndef _SWALLOW_H_
#define _SWALLOW_H_

#include "speaker.h"

static const Speaker_Note swallow[] = {
    {NOTE_CS5, 779},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {0, 97},
    {NOTE_D5, 97},
    {0, 97},
    {NOTE_AS4, 97},
    {0, 97},
    {NOTE_G4, 97},
    
    {NOTE_F4, 487},
    {0, 97},
    {NOTE_F3, 97},
    {NOTE_G3, 97},
    {NOTE_GS3, 97},
    {NOTE_A3, 97},
    {NOTE_GS3, 97},
    {NOTE_F3, 97},
    {NOTE_GS3, 97},
    {NOTE_F3, 97},
    {NOTE_G3, 97},
    {NOTE_GS3, 97},
    
    {NOTE_A3, 97},
    {NOTE_AS3, 97},
    {NOTE_C4, 65},
    {NOTE_CS4, 65},
    {NOTE_C4, 65},
    {NOTE_AS3, 97},
    {NOTE_C4, 97},
    {NOTE_A3, 97},
    {NOTE_AS3, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_FS4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_B4, 97},
    
    {NOTE_C5, 97},
    {NOTE_B4, 97},
    {NOTE_AS4, 97},
    {NOTE_A4, 97},
    {NOTE_GS4, 97},
    {NOTE_G4, 97},
    {NOTE_FS4, 97},
    {NOTE_F4, 97},
    {NOTE_E4, 97},
    {NOTE_DS4, 97},
    {NOTE_D4, 97},
    {NOTE_C4, 97},
    {NOTE_CS4, 97},
    {NOTE_C4, 97},
    {NOTE_B3, 97},
    
    {NOTE_C4, 195},
    {NOTE_AS3, 97},
    {NOTE_C4, 97},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_E5, 97},
    {NOTE_DS5, 97},
    {NOTE_C5, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    
    {NOTE_GS4, 97},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_E4, 97},
    {NOTE_F4, 97},
    {NOTE_C4, 97},
    {NOTE_CS4, 97},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_FS4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_D4, 97},
    
    {NOTE_DS4, 97},
    {NOTE_C4, 97},
    {NOTE_CS4, 97},
    {NOTE_D4, 97},
    {NOTE_CS4, 97},
    {NOTE_C4, 97},
    {NOTE_GS3, 97},
    {NOTE_FS3, 97},
    {NOTE_GS3, 97},
    {NOTE_A3, 97},
    {NOTE_GS3, 97},
    {NOTE_E3, 97},
    {NOTE_DS3, 97},
    {NOTE_CS3, 97},
    {NOTE_D3, 97},
    {NOTE_DS3, 97},
    
    {NOTE_DS3, 97},
    {104, 97},
    {92, 97},
    {98, 97},
    {104, 97},
    {123, 97},
    {NOTE_C3, 97},
    {NOTE_CS3, 97},
    {110, 97},
    {104, 97},
    {104, 97},
    {NOTE_C3, 97},
    {NOTE_CS3, 97},
    {NOTE_DS3, 97},
    {NOTE_F3, 97},
    {NOTE_FS3, 97},
    
    {NOTE_GS3, 97},
    {NOTE_B3, 65},
    {NOTE_C4, 130},
    {NOTE_DS4, 97},
    {NOTE_E4, 65},
    {NOTE_FS4, 130},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_GS4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_D4, 97},
    {NOTE_CS4, 97},
    {NOTE_C4, 97},
    
    {NOTE_CS4, 97},
    {NOTE_E4, 97},
    {NOTE_F4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_G4, 97},
    {NOTE_E4, 97},
    {NOTE_DS4, 97},
    {NOTE_E4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_A4, 97},
    {NOTE_F4, 97},
    
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_B4, 97},
    {NOTE_G4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_A4, 97},
    {NOTE_B4, 97},
    {NOTE_CS5, 97},
    {NOTE_A4, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_B4, 97},
    {NOTE_CS5, 97},
    
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_E4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    
    {NOTE_C4, 97},
    {NOTE_D4, 97},
    {NOTE_C4, 292},
    {NOTE_CS4, 292},
    {NOTE_DS4, 292},
    {NOTE_G4, 292},
    {NOTE_CS5, 97},
    {0, 97},
    
    {NOTE_D5, 390},
    {NOTE_AS4, 195},
    {NOTE_G4, 390},
    {NOTE_F4, 195},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {0, 97},
    
    {NOTE_D4, 487},
    {NOTE_AS3, 195},
    {NOTE_G3, 390},
    {NOTE_F3, 195},
    {NOTE_DS3, 97},
    {NOTE_F3, 97},
    {0, 97},
    
    {NOTE_D3, 195},
    {NOTE_DS3, 97},
    {NOTE_D3, 97},
    {NOTE_C3, 97},
    {NOTE_D3, 97},
    {117, 97},
    {NOTE_C3, 97},
    {NOTE_D3, 97},
    {NOTE_DS3, 97},
    {NOTE_C3, 97},
    {NOTE_D3, 97},
    {NOTE_DS3, 97},
    {NOTE_F3, 97},
    {NOTE_D3, 97},
    {NOTE_DS3, 97},
    {NOTE_F3, 97},
    
    {NOTE_G3, 195},
    {NOTE_F3, 97},
    {NOTE_G3, 97},
    {NOTE_GS3, 97},
    {NOTE_F3, 97},
    {NOTE_G3, 97},
    {NOTE_GS3, 97},
    {NOTE_AS3, 97},
    {NOTE_G3, 97},
    {NOTE_GS3, 97},
    {NOTE_AS3, 97},
    {NOTE_C4, 97},
    {NOTE_C4, 97},
    {NOTE_AS3, 97},
    {NOTE_C4, 97},
    
    {NOTE_AS3, 97},
    {NOTE_AS3, 97},
    {NOTE_C4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_C4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    
    {NOTE_DS5, 292},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_AS4, 97},
    {NOTE_AS4, 195},
    {NOTE_AS4, 97},
    {NOTE_A4, 97},
    {NOTE_GS4, 97},
    {NOTE_G4, 97},
    {NOTE_FS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_E4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_AS3, 97},
    {NOTE_DS4, 97},
    {NOTE_AS3, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_GS4, 97},
    {NOTE_C5, 97},
    {NOTE_DS5, 97},
    {NOTE_C5, 97},
    {NOTE_C5, 97},
    
    {NOTE_DS5, 292},
    {NOTE_DS5, 97},
    {NOTE_CS5, 487},
    {0, 97},
    {NOTE_A4, 244},
    {NOTE_FS5, 49},
    {NOTE_F5, 97},
    {NOTE_GS5, 97},
    {0, 97},
    
    {NOTE_GS5, 974},
    {0, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    
    {NOTE_G5, 195},
    {NOTE_DS5, 97},
    {NOTE_E5, 97},
    {NOTE_F5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_CS5, 195},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    
    {NOTE_CS5, 97},
    {NOTE_AS4, 97},
    {NOTE_B4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    {NOTE_C4, 97},
    {NOTE_AS3, 97},
    {NOTE_A3, 97},
    
    {NOTE_B3, 195},
    {NOTE_F4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_CS4, 97},
    {NOTE_G4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_AS3, 97},
    {NOTE_F4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_CS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    
    {NOTE_D4, 97},
    {NOTE_A4, 97},
    {NOTE_DS4, 97},
    {NOTE_D4, 195},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_A4, 97},
    {NOTE_E4, 97},
    {NOTE_DS4, 97},
    {NOTE_E4, 97},
    {NOTE_B4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_DS4, 97},
    {NOTE_A4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_B4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_CS5, 97},
    {NOTE_A4, 97},
    {NOTE_F4, 97},
    {NOTE_F4, 97},
    {NOTE_B4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    
    {NOTE_G4, 97},
    {NOTE_CS5, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_A4, 97},
    {NOTE_DS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_B4, 97},
    {NOTE_F5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 292},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_B4, 97},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_B4, 97},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_B4, 97},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    
    {NOTE_B4, 195},
    {0, 97},
    {0, 195},
    {0, 390},
    {0, 779},
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
};

static const uint16_t swallow_len = (uint16_t)(sizeof(swallow)/sizeof(swallow[0]));

#endif /* _SWALLOW_H_ */
