// Generated by musicxml_to_speaker_notes.py
// From ./swallow2.musicxml, tempo=154.0
#ifndef _SWALLOW_H_
#define _SWALLOW_H_

#include "speaker.h"

static const Speaker_Note swallow[] = {
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_B4, 97},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_B4, 97},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    {NOTE_B4, 97},
    
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 195},
    {NOTE_G4, 97},
    {NOTE_D5, 97},
    {NOTE_AS4, 97},
    {NOTE_G4, 97},
    {NOTE_DS4, 97},
    
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_CS5, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 195},
    {NOTE_F4, 97},
    {NOTE_C5, 97},
    {NOTE_GS4, 97},
    {NOTE_F4, 97},
    
    {NOTE_C4, 195},
    {NOTE_D4, 97},
    {NOTE_DS4, 97},
    {NOTE_F4, 97},
    {NOTE_G4, 97},
    {NOTE_GS4, 97},
    {NOTE_AS4, 97},
    {NOTE_C5, 97},
    {NOTE_D5, 97},
    {NOTE_DS5, 97},
    {NOTE_F5, 97},
    {NOTE_G5, 97},
    {NOTE_GS5, 97},
    {NOTE_AS5, 97},
    {0, 97},
    
    {NOTE_B5, 195},
    {NOTE_A5, 97},
    {NOTE_G5, 97},
    {NOTE_F5, 97},
    {NOTE_DS5, 97},
    {NOTE_CS5, 97},
    {NOTE_B4, 97},
    {NOTE_A4, 97},
    {NOTE_G4, 97},
    {NOTE_F4, 97},
    {NOTE_DS4, 97},
    {NOTE_CS4, 97},
    {NOTE_B3, 97},
    {NOTE_E4, 97},
    {NOTE_G4, 97},
    
    {NOTE_B4, 195},
    {0, 97},
    {0, 195},
    {0, 390},
    {0, 779},
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
};

static const uint16_t swallow_len = (uint16_t)(sizeof(swallow)/sizeof(swallow[0]));

#endif /* _SWALLOW_H_ */
